# --- STAGE 1: Build React static assets using Node.js ---
FROM node:18-alpine AS builder
WORKDIR /app

# Cache node modules
COPY package.json package-lock.json* ./
RUN npm install

# Build static website
COPY . .
RUN npm run build

# --- STAGE 2: Serve static website using Nginx ---
FROM nginx:1.25-alpine
WORKDIR /usr/share/nginx/html

# Clean default assets
RUN rm -rf ./*

# Copy built code from builder stage to Nginx directory
COPY --from=builder /app/build .

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]
