database.url=jdbc:mysql://localhost:3306/uniqlo_education
database.username=root
database.password=root
database.driver-class-name=com.mysql.cj.jdbc.Driver
database.max-pool-size=10
database.min-idle=5
database.idle-timeout=30000
database.connection-timeout=30000
database.max-lifetime=1800000
database.pool-name=HikariCP
