spring.application.name=uniqlo-service-v1

# config k?t n?i database => t? ??ng spring s? ??c các config và t?o bean DataSource ?? k?t n?i ??n database,
# không c?n ph?i t?o file config, có t? t? config b?ng class nh? spring mvc ho?c có th? config
# 1 service spring boot connect ??n 2 ho?c nhi?u database, ch? c?n t?o config b?ng class cho các datasource,
# m?i 1 object datasource chính là dành cho 1 database
spring.datasource.url=jdbc:mysql://localhost:3306/uniqlo_education?useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# config hikari connection pool
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# config JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# Allow SessionFactory.getCurrentSession() with Spring-managed transactions
spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
